<?php
/**
 * Implements hook_library().
 * for use $element['#attached']['library'][] = array('csas_owl', 'csas_owl_carousel'); && drupal_add_library('csas_owl', 'csas_owl_carousel');
 */
function csas_owl_library() {
  $m_path = drupal_get_path('module', 'csas_owl');
  $library_path = csas_owl_get_owlcarousel2_path();
  $css_m_file = _csas_owl_get_css_m_file('csas_owl.css');
  $libraries['csas_owl_carousel'] = array(
    'title' => 'Owl carousel',
    'version' => '2.2.1',
    'description' => 'https://github.com/smashingboxes/OwlCarousel2',
    'js' => array(
      $library_path . '/assets/vendors/jquery.mousewheel.min.js' => array(),
      $library_path . '/owl.carousel.min.js' => array(),
      $m_path . '/js/csas_owl.js' => array('scope' => 'footer'),
    ),
    'css' => array(
      $library_path . '/assets/owl.carousel.min.css' => array(),
      $library_path . '/assets/owl.theme.default.min.css' => array(),
      $css_m_file => array(),
    )
  );
  return $libraries;
}

function _csas_owl_get_css_m_file($fle = '') {
  global $theme;
  $pth = drupal_get_path('theme', $theme);
  $dta = $pth . '/css/' . $theme . '.' . $fle;
  if (file_exists($dta)) {
    return $dta;
  }
  else {
    $pth = drupal_get_path('module', 'csas_owl');
    return $pth . "/css/{$fle}";
  }
}

/**
 * Get the location of the chosen library.
 *
 * @return
 *   The location of the library, or FALSE if the library isn't installed.
 */
function csas_owl_get_owlcarousel2_path() {
  if (function_exists('libraries_get_path')) {
    return libraries_get_path('owlcarousel2');
  }

  // The following logic is taken from libraries_get_libraries()
  $searchdir = array();

  // Similar to 'modules' and 'themes' directories inside an installation
  // profile, installation profiles may want to place libraries into a
  // 'libraries' directory.
  $searchdir[] = 'profiles/' . drupal_get_profile() . '/libraries';

  // Always search sites/all/libraries.
  $searchdir[] = 'sites/all/libraries';

  // Also search sites/<domain>/*.
  $searchdir[] = conf_path() . '/libraries';

  foreach ($searchdir as $dir) {
    if (file_exists($dir . '/owlcarousel2/owl.carousel.min.js')) {
      return $dir . '/owlcarousel2';
    }
  }

  return FALSE;
}

function csas_owl_menu(){
  $items['csas-owl-example'] = array(
    'title' => 'Csas oWl example',
    'page callback' => 'csas_owl_pages_example',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'csas_owl.pages.inc',
  );
  return $items;
}